/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Random seed set as 42
Traceback (most recent call last):
  File "/vast/home/ajherman/continualEP/main.py", line 8, in <module>
    from netClasses import *
  File "/vast/home/ajherman/continualEP/netClasses.py", line 10, in <module>
    from main import rho, rhop
  File "/vast/home/ajherman/continualEP/main.py", line 92, in <module>
    peraser.add_argument(
    ^^^^^^^
NameError: name 'peraser' is not defined. Did you mean: 'parser'?
/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Random seed set as 42
usage: main.py [-h] [--batch-size N] [--test-batch-size N] [--epochs N]
               [--lr_tab LR [LR ...]] [--randbeta RANDBETA]
               [--size_tab ST [ST ...]] [--discrete] [--N1 N1] [--N2 N2]
               [--max-Q MAX_Q] [--beta BETA] [--n-dynamic N_DYNAMIC]
               [--n-trace N_TRACE] [--activation-function ACTFUN] [--no-clamp]
               [--learning-rule LR] [--cep] [--action ACTION]
               [--device-label DEVICE_LABEL] [--debug-cep]
               [--seed SEED [SEED ...]] [--use-bias] [--no-rhop]
               [--update-rule UPDATE_RULE] [--no-reset] [--plain-data]
               [--trace-decay TRACE_DECAY] [--directory DIRECTORY] [--load]
               [--spiking] [--T1 T1] [--T2 T2] [--max-fr MAX_FR] [--step STEP]
               [--tau-dynamic TAU_DYNAMIC] [--tau-trace TAU_TRACE] [--dt DT]
               [--spike-height SPIKE_HEIGHT]
main.py: error: argument --tau-dynamic: expected one argument
/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Random seed set as 42
dt =  0.3934693402873666
trace decay =  0.6065306597126334
Random seed set as 42
Random seed set as 42
dt =  0.3934693402873666
trace decay =  0.6065306597126334
Random seed set as 42
Traceback (most recent call last):
  File "/vast/home/ajherman/continualEP/main.py", line 457, in <module>
    error_train = train(net, train_loader, epoch, args.learning_rule)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netFunctions.py", line 98, in train
    s,deltas = net.forward(data, s, return_deltas=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netClasses.py", line 134, in forward
    s,dsdt = self.stepper(data, s)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netClasses.py", line 71, in stepper
    spike = [self.spike_height*(torch.rand(si.size(),device=self.device)<(rho(si)*self.Q/self.spike_height)).float() for si in s] # Get Poisson spikes
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netClasses.py", line 71, in <listcomp>
    spike = [self.spike_height*(torch.rand(si.size(),device=self.device)<(rho(si)*self.Q/self.spike_height)).float() for si in s] # Get Poisson spikes
                                                                                  ^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SNN' object has no attribute 'Q'
/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Random seed set as 42
dt =  0.3934693402873666
trace decay =  0.6065306597126334
Random seed set as 42
Random seed set as 42
dt =  0.3934693402873666
trace decay =  0.6065306597126334
Random seed set as 42
Traceback (most recent call last):
  File "/vast/home/ajherman/continualEP/main.py", line 457, in <module>
    error_train = train(net, train_loader, epoch, args.learning_rule)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netFunctions.py", line 98, in train
    s,deltas = net.forward(data, s, return_deltas=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netClasses.py", line 134, in forward
    s,dsdt = self.stepper(data, s)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netClasses.py", line 71, in stepper
    spike = [self.spike_height*(torch.rand(si.size(),device=self.device)<(rho(si)*self.Q/self.spike_height)).float() for si in s] # Get Poisson spikes
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netClasses.py", line 71, in <listcomp>
    spike = [self.spike_height*(torch.rand(si.size(),device=self.device)<(rho(si)*self.Q/self.spike_height)).float() for si in s] # Get Poisson spikes
                                                                                  ^^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SNN' object has no attribute 'Q'
/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Random seed set as 42
dt =  0.3934693402873666
trace decay =  0.6065306597126334
Random seed set as 42
Random seed set as 42
dt =  0.3934693402873666
trace decay =  0.6065306597126334
Random seed set as 42
Traceback (most recent call last):
  File "/vast/home/ajherman/continualEP/main.py", line 457, in <module>
    error_train = train(net, train_loader, epoch, args.learning_rule)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/home/ajherman/continualEP/netFunctions.py", line 119, in train
    ax.plot(np.arange(net.T),deltas)
                      ^^^^^
  File "/vast/home/ajherman/miniconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SNN' object has no attribute 'T'
